name: Generate Podcast Feeds
on: [push] #when someone pushes a change onto main branch in repository it will execute this action
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: jarredstumberg/podcast-generator@main
      
